package com.ppms.notification;

import com.ppms.ancillary.AncillaryProductRepository;
import com.ppms.ancillary.AncillaryProductStatus;
import com.ppms.document.PumpDocumentRepository;
import com.ppms.fuel.GlobalFuelPriceRepository;
import com.ppms.inventory.TankStockResponse;
import com.ppms.pump.NozzleCalibrationLogRepository;
import com.ppms.pump.TankStatus;
import com.ppms.pump.UndergroundTankRepository;
import com.ppms.shift.Shift;
import com.ppms.shift.ShiftRepository;
import com.ppms.shift.ShiftStatus;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.Duration;
import java.time.LocalDate;
import java.util.List;

/**
 * Generates in-app notifications for pump alert conditions.
 *
 * Notifications are generated by a background scheduler (NotificationGenerationJob)
 * every 5 minutes for all active pumps. The GET /notifications endpoint serves
 * pre-computed results from the DB without triggering any generation logic.
 *
 * Dedup by (pump_id, dedup_key): each alert condition produces at most one unread
 * notification. Duplicate INSERTs are silently ignored by the unique constraint.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class NotificationService {

    private final NotificationRepository notificationRepository;
    private final PumpDocumentRepository documentRepository;
    private final GlobalFuelPriceRepository fuelPriceRepository;
    private final ShiftRepository shiftRepository;
    private final AncillaryProductRepository ancillaryProductRepository;
    private final UndergroundTankRepository tankRepository;
    private final NozzleCalibrationLogRepository calibrationLogRepository;
    private final NotificationDedupService dedupService;

    // No class-level TODAY constant — LocalDate.now() is always called inline so it reflects
    // the actual current date when the method runs, not the date the class was loaded.

    /**
     * Generates all notifications for a pump by checking current system state.
     * Called by NotificationGenerationJob on a schedule (not by the API endpoint).
     */
    @Transactional
    public void generateNotificationsForPump(Long pumpId) {
        List<TankStockResponse> tankStocks = computeTankStocks(pumpId);
        generateLowStockAlerts(pumpId, tankStocks);
        generatePriceStalenessAlerts(pumpId);
        generateDocumentExpiryAlerts(pumpId);
        generateZeroSaleAlerts(pumpId);
        generateAutoClosedShiftAlerts(pumpId);
        generateAncillaryLowStockAlerts(pumpId);
        generateCalibrationDueAlerts(pumpId);
        log.debug("Notification generation complete for pump={}", pumpId);
    }

    /**
     * Returns all unread notifications for a pump. Does NOT generate new ones —
     * generation is handled by NotificationGenerationJob on a background schedule.
     */
    public List<Notification> getUnreadNotifications(Long pumpId) {
        return notificationRepository.findByPumpIdAndReadAtIsNullOrderByCreatedAtDesc(pumpId);
    }

    /**
     * Computes current tank stock summaries for a pump.
     * Used internally for low-stock alert generation.
     */
    private List<TankStockResponse> computeTankStocks(Long pumpId) {
        return tankRepository.findByPumpId(pumpId).stream()
                .filter(t -> t.getStatus() != TankStatus.DECOMMISSIONED)
                .map(tank -> {
                    BigDecimal stock    = tank.getCurrentStock() != null ? tank.getCurrentStock() : BigDecimal.ZERO;
                    BigDecimal capacity = tank.getCapacity();
                    BigDecimal pct = capacity.compareTo(BigDecimal.ZERO) > 0
                            ? stock.multiply(new BigDecimal("100"))
                                   .divide(capacity, 1, RoundingMode.HALF_UP)
                            : BigDecimal.ZERO;
                    return TankStockResponse.builder()
                            .tankId(tank.getId())
                            .tankIdentifier(tank.getTankIdentifier())
                            .fuelType(tank.getFuelType().name())
                            .capacity(capacity.setScale(3, RoundingMode.HALF_UP))
                            .currentStock(stock.setScale(3, RoundingMode.HALF_UP))
                            .stockPercentage(pct)
                            .lowStock(pct.compareTo(new BigDecimal("20")) < 0)
                            .pumpId(tank.getPumpId())
                            .status(tank.getStatus().name())
                            .build();
                })
                .toList();
    }

    /**
     * Marks all unread notifications for a pump as read.
     */
    @Transactional
    public void markAllRead(Long pumpId) {
        notificationRepository.markAllReadForPump(pumpId);
    }

    // ── Private generation helpers ────────────────────────────────────────────

    private void generateLowStockAlerts(Long pumpId, List<TankStockResponse> tanks) {
        tanks.stream()
                .filter(TankStockResponse::isLowStock)
                .forEach(tank -> {
                    String dedupKey = "LOW_STOCK:tank:" + tank.getTankId();
                    dedupService.maybeInsert(pumpId, NotificationType.LOW_STOCK, dedupKey,
                            "Low Tank Stock",
                            tank.getTankIdentifier() + " (" + tank.getFuelType() + ") is at "
                                    + String.format("%.1f", tank.getStockPercentage().doubleValue()) + "% — delivery needed.");
                });
    }

    private void generatePriceStalenessAlerts(Long pumpId) {
        // Alert only when NO prices have ever been configured for this pump.
        // A price set on a previous day remains the valid current price — that is normal
        // for a petrol pump where government-issued prices can stay unchanged for weeks.
        // The old condition `effectiveFrom.isBefore(today)` was wrong: it fired every day
        // for any pump that had already set prices, creating spam notifications.
        var currentPrices = fuelPriceRepository.findCurrentPricesForPump(pumpId);
        if (currentPrices.isEmpty()) {
            LocalDate today = LocalDate.now();
            // Daily dedup key — re-alerts each day until at least one price is configured.
            String dedupKey = "PRICE_STALE:" + today;
            dedupService.maybeInsert(pumpId, NotificationType.PRICE_STALE, dedupKey,
                    "Fuel Prices Not Configured",
                    "No fuel prices have been set for this pump yet. Go to Setup → Fuel Prices to configure them.");
        }
    }

    private void generateDocumentExpiryAlerts(Long pumpId) {
        LocalDate today     = LocalDate.now();
        LocalDate threshold = today.plusDays(30);

        documentRepository.findByPumpIdOrderByExpiryDateAsc(pumpId).stream()
                .filter(doc -> doc.getExpiryDate() != null
                        && !doc.getExpiryDate().isAfter(threshold))
                .forEach(doc -> {
                    String dedupKey = "DOCUMENT_EXPIRING:doc:" + doc.getId();
                    boolean expired = doc.getExpiryDate().isBefore(today);
                    String title   = expired ? "Document Expired" : "Document Expiring Soon";
                    String message = doc.getName() + " (" + doc.getDocType() + ") "
                            + (expired ? "expired on " : "expires on ") + doc.getExpiryDate();
                    dedupService.maybeInsert(pumpId, NotificationType.DOCUMENT_EXPIRING, dedupKey, title, message);
                });
    }

    /**
     * P2.4 — Generates a ZERO_SALE_SHIFT alert for each closed shift today where:
     *   - total_amount_due == 0 (no sales recorded)
     *   - shift duration > 30 minutes (too long to be a test or accidental open)
     *
     * This pattern strongly suggests the operator entered the same opening and closing
     * meter readings to hide actual sales — a common petrol pump fraud signal.
     * One alert per shift is generated using the shift ID as the dedup key.
     */
    private void generateZeroSaleAlerts(Long pumpId) {
        LocalDate today = LocalDate.now();
        List<Shift> todayShifts = shiftRepository.findClosedShiftsByDate(pumpId, today);

        todayShifts.stream()
                .filter(shift -> shift.getTotalAmountDue() != null
                        && shift.getTotalAmountDue().compareTo(BigDecimal.ZERO) == 0
                        && shift.getActualStartTime() != null
                        && shift.getActualEndTime() != null
                        && Duration.between(shift.getActualStartTime(), shift.getActualEndTime()).toMinutes() > 30)
                .forEach(shift -> {
                    String dedupKey = "ZERO_SALE_SHIFT:shift:" + shift.getId();
                    dedupService.maybeInsert(pumpId, NotificationType.ZERO_SALE_SHIFT, dedupKey,
                            "Zero-Sale Shift Detected",
                            "Shift #" + shift.getId() + " on Nozzle was open for over 30 minutes but recorded ₹0 in sales. " +
                            "This may indicate a data entry error or missing readings. Please review.");
                });
    }

    /**
     * Generates AUTO_CLOSED_SHIFT alerts for shifts that the OverdueShiftJob force-closed today.
     * These shifts are in AUTO_CLOSED_OVERDUE status and have no end-meter readings,
     * meaning management must perform a manual reconciliation.
     * Dedup key is per shift ID — one alert per affected shift.
     */
    private void generateAutoClosedShiftAlerts(Long pumpId) {
        LocalDate today = LocalDate.now();
        shiftRepository.findClosedShiftsByDate(pumpId, today).stream()
                .filter(shift -> shift.getStatus() == ShiftStatus.AUTO_CLOSED_OVERDUE)
                .forEach(shift -> {
                    String dedupKey = "AUTO_CLOSED_SHIFT:shift:" + shift.getId();
                    dedupService.maybeInsert(pumpId, NotificationType.AUTO_CLOSED_SHIFT, dedupKey,
                            "Shift Force-Closed Without Readings",
                            "Shift #" + shift.getId() + " was automatically closed because the operator never submitted " +
                            "closing meter readings. End-meter data is missing — a manual reconciliation is required.");
                });
    }

    /**
     * Generates CALIBRATION_DUE alerts for nozzles whose most-recent calibration record
     * has a next_calibration_due date that is today or in the past.
     * The query returns only the latest log per nozzle (not superseded records),
     * so each nozzle fires at most one alert.
     * Dedup key is per nozzle ID — the alert stays active until the nozzle is re-calibrated.
     */
    private void generateCalibrationDueAlerts(Long pumpId) {
        calibrationLogRepository.findOverdueCalibrations(pumpId, LocalDate.now())
                .forEach(log -> {
                    String dedupKey = "CALIBRATION_DUE:nozzle:" + log.getNozzleId();
                    String message = "Nozzle #" + log.getNozzleId() + " calibration was due on "
                            + log.getNextCalibrationDue() + ". Please schedule a calibration to remain compliant.";
                    dedupService.maybeInsert(pumpId, NotificationType.CALIBRATION_DUE, dedupKey,
                            "Nozzle Calibration Overdue", message);
                });
    }

    /**
     * Generates ANCILLARY_LOW_STOCK alerts for active products whose current stock
     * is at or below their configured low_stock_threshold.
     * Products with no threshold (null) are skipped — the alert is opt-in per product.
     * Dedup key is per product ID so each product generates at most one pending alert.
     */
    private void generateAncillaryLowStockAlerts(Long pumpId) {
        ancillaryProductRepository.findByPumpIdAndStatusOrderByNameAsc(pumpId, AncillaryProductStatus.ACTIVE)
                .stream()
                .filter(p -> p.getLowStockThreshold() != null
                        && p.getCurrentStockUnits() <= p.getLowStockThreshold())
                .forEach(p -> {
                    String dedupKey = "ANCILLARY_LOW_STOCK:product:" + p.getId();
                    String displayName = (p.getBrand() != null ? p.getBrand() + " " : "") + p.getName();
                    dedupService.maybeInsert(pumpId, NotificationType.ANCILLARY_LOW_STOCK, dedupKey,
                            "Low Product Stock",
                            displayName + " has only " + p.getCurrentStockUnits()
                            + " unit(s) remaining (threshold: " + p.getLowStockThreshold() + "). Restock soon.");
                });
    }
}
